export const FETCH_GENRES = 'FETCH_GENRES';
export const FETCH_GENRES_SUCCESS = 'FETCH_GENRES_SUCCESS';
export const FETCH_GENRES_FAILED = 'FETCH_GENRES_FAILED';

export const ADD_BOOKS = 'ADD_BOOKS';
export const ADD_BOOKS_SUCCESS = 'ADD_BOOKS_SUCCESS';
export const ADD_BOOKS_FAILED = 'ADD_BOOKS_FAILED';

export const UPDATE_BOOKS_BY_GENRE = 'UPDATE_BOOKS_BY_GENRE';
export const UPDATE_ALL_BOOKS = 'UPDATE_ALL_BOOKS';